<a href="https://colab.research.google.com/github/Alpinnnn/Alpinnnn/blob/main/Data_Analiytics_%26_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {'Nama': ['John', 'Anna', 'Peter', 'Linda'],
        "Usia": [28, 35, 40, 32],
        "Kota": ['New York', 'Paris', 'Berlin', 'London']}

df = pd.DataFrame(data)
df.head()

    Nama  Usia      Kota
0   John    28  New York
1   Anna    35     Paris
2  Peter    40    Berlin
3  Linda    32    London

In [3]:
import pandas as pd

In [4]:
student_data = pd.read_csv('student_data.csv')

In [ ]:
student_data.head(3)

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
0,Alan Ferrell,A,131.433702,62.469138,2005-10-06,75,23,96,88,1,2,78,51,60
1,Lindsay Coffey,B,160.972880,44.525710,2005-12-21,26,95,93,73,57,10,5,93,77
2,Mitchell Bennett,A,132.967250,93.559249,2005-08-30,51,93,89,56,36,8,6,18,5

In [ ]:
student_data.size

4200

In [ ]:
student_data.shape

(300, 14)

In [ ]:
student_data.columns

Index(['Name', 'Group', 'Height', 'Weight', 'Date_of_Birth',
       'Maths_Test_Score', 'Maths_Quiz_Score', 'Maths_Assignment_Score',
       'Science_Test_Score', 'Science_Quiz_Score', 'Science_Assignment_Score',
       'Literature_Test_Score', 'Literature_Quiz_Score',
       'Literature_Assignment_Score'],
      dtype='object')

In [ ]:
student_data.iloc[2]

Name                           Mitchell Bennett
Group                                         A
Height                                132.96725
Weight                                93.559249
Date_of_Birth                        2005-08-30
Maths_Test_Score                             51
Maths_Quiz_Score                             93
Maths_Assignment_Score                       89
Science_Test_Score                           56
Science_Quiz_Score                           36
Science_Assignment_Score                      8
Literature_Test_Score                         6
Literature_Quiz_Score                        18
Literature_Assignment_Score                   5
Name: 2, dtype: object

In [ ]:
student_data.iloc[100:121]

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
100,Mr. William Brown,B,182.620124,43.866008,2004-06-20,44,25,50,54,7,13,26,85,37
101,Brooke Downs,C,180.350677,44.466420,2006-03-19,5,65,100,76,66,13,35,74,73
102,James Archer,C,163.550983,77.712212,2006-10-24,75,85,57,85,68,20,95,93,83
103,Kimberly Weiss,A,138.716450,58.393847,2005-12-23,76,73,23,95,97,23,2,73,86
104,Nicholas Stevens,B,185.189698,80.220606,2006-10-18,84,95,3,26,48,17,85,30,97
105,Natalie Daniels,A,180.376300,49.575043,2005-03-30,5,91,31,76,76,30,84,84,31
106,Monica Lawson,C,189.007582,98.174114,2006-11-07,100,43,27,31,77,20,96,55,80
107,Rachel Clarke,B,145.541867,38.314185,2004-05-11,64,44,0,40,29,0,15,8,58
108,Sarah Shaw,B,165.219758,93.355120,2005-07-12,82,51,25,43,44,27,60,97,61
109,Matthew Gregory,C,134.952631,45.940474,2005-03-17,25,14,66,3,91,30,78,88,14
110,Megan Herrera,C,189.853357,79.622058,2006-10-31,30,58,45,47,94,16,84,58,79
111,Stephen Francis,C,145.461921,86.924745,2007-04-24,88,91,19,73,63,14,13,22,5
112,Rebecca Leonard,C,131.954068,43.677392,2006-06-20,4,91,9,82,85,21,74,10,7
113,Lori Collins,B,142.458873,94.913568,2005-06-30,17,52,76,86,16,2,83,53,16
114,Rhonda Norman,B,183.570815,55.633422,2004-06-15,87,67,93,39,95,20,87,32,90
115,George Edwards,B,156.819334,52.445568,2005-12-27,46,89,57,5,65,6,68,13,0
116,Brian Hicks,A,177.920751,47.726049,2007-03-23,34,44,81,39,94,8,88,32,28
117,Richard Little,B,189.511972,71.599459,2005-02-01,65,8,40,60,10,25,15,78,82
118,Austin Chavez,C,181.360184,56.168327,2006-12-04,14,21,51,9,10,25,52,86,12
119,Jeremy Taylor,A,170.505545,50.525915,2007-01-28,83,89,87,51,69,14,35,4,48
120,Kevin Campbell,B,162.123804,93.510788,2005-01-30,49,0,12,3,23,13,60,72,92

In [ ]:
student_data.Name

0          Alan Ferrell
1        Lindsay Coffey
2      Mitchell Bennett
3           Dawn Porter
4           Ashley Huff
             ...
295       Shannon Hardy
296    Christopher Ware
297    Christina Thomas
298        Mark Esparza
299      William Foster
Name: Name, Length: 300, dtype: object

In [ ]:
student_data['Name']

0          Alan Ferrell
1        Lindsay Coffey
2      Mitchell Bennett
3           Dawn Porter
4           Ashley Huff
             ...
295       Shannon Hardy
296    Christopher Ware
297    Christina Thomas
298        Mark Esparza
299      William Foster
Name: Name, Length: 300, dtype: object

In [ ]:
student_data[['Name', 'Group']]

                 Name Group
0        Alan Ferrell     A
1      Lindsay Coffey     B
2    Mitchell Bennett     A
3         Dawn Porter     A
4         Ashley Huff     C
..                ...   ...
295     Shannon Hardy     B
296  Christopher Ware     A
297  Christina Thomas     C
298      Mark Esparza     C
299    William Foster     B

[300 rows x 2 columns]

In [ ]:
student_data.loc[3,["Name", "Group", "Height"]]

Name      Dawn Porter
Group               A
Height     160.481596
Name: 3, dtype: object

In [ ]:
student_data[student_data ["Group"] == 'A']

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
0,Alan Ferrell,A,131.433702,62.469138,2005-10-06,75,23,96,88,1,2,78,51,60
2,Mitchell Bennett,A,132.967250,93.559249,2005-08-30,51,93,89,56,36,8,6,18,5
3,Dawn Porter,A,160.481596,36.408254,2004-10-21,67,95,89,60,56,17,5,21,80
5,Clinton Dawson,A,173.524653,66.801124,2005-06-03,26,16,37,34,62,27,95,32,64
8,Tyler Meyer,A,133.860132,92.013826,2005-06-14,33,20,7,29,31,17,32,95,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,Carol Palmer,A,185.948742,69.342926,2004-11-21,12,51,16,77,52,0,81,32,20
285,Michelle Carson,A,148.757399,76.580334,2006-06-15,62,19,84,95,68,0,85,51,41
286,Sarah Smith,A,151.540240,68.237031,2006-09-12,55,73,49,66,78,24,12,40,63
292,Ryan Arnold,A,138.557409,45.726217,2006-08-25,58,86,22,84,32,27,49,72,88
296,Christopher Ware,A,152.802949,44.157204,2006-08-31,24,65,22,99,78,13,80,87,2

In [ ]:
student_data[
    (student_data["Group"]=='A') & (student_data["Height"]>160)
]

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
3,Dawn Porter,A,160.481596,36.408254,2004-10-21,67,95,89,60,56,17,5,21,80
5,Clinton Dawson,A,173.524653,66.801124,2005-06-03,26,16,37,34,62,27,95,32,64
16,Ruben Morales,A,164.569543,40.830899,2006-07-09,20,41,100,24,89,28,43,38,91
17,Dr. Paul Thompson,A,168.423981,62.205048,2004-12-10,88,77,73,24,2,3,48,69,77
21,Barbara Espinoza,A,175.763004,48.991579,2005-05-26,41,98,69,14,74,0,91,36,28
23,Tina Yang,A,183.077127,76.112455,2007-02-17,25,18,77,13,58,9,54,90,52
31,Amy Tran,A,182.486363,55.403956,2004-07-09,15,97,73,20,38,24,14,22,94
37,John Garza,A,188.048438,85.378761,2004-10-15,90,16,92,86,44,26,54,33,65
41,Alexander Fox,A,166.251512,56.331331,2006-07-19,95,73,62,11,55,18,90,66,27
42,Brian Harris,A,172.427313,57.523992,2005-12-24,6,16,21,71,17,6,60,31,92
46,David Leon,A,181.942900,85.597578,2006-02-27,69,83,33,47,25,14,32,57,37
51,Olivia Hughes,A,160.679096,36.983216,2007-04-18,20,17,9,78,68,30,100,23,32
52,Mark Hernandez,A,188.498185,43.124576,2006-10-08,61,13,53,71,30,16,55,57,27
60,Scott Harris,A,176.481059,40.881294,2005-01-23,55,88,53,16,64,19,70,50,98
63,Andrew Stewart,A,187.491549,39.225933,2005-11-12,90,12,75,66,36,3,73,96,12
68,Brian Jones,A,187.507421,97.606327,2005-08-01,29,79,100,16,40,6,61,52,65
72,Deanna Thomas,A,166.981193,65.702935,2006-01-09,0,64,85,72,49,12,30,14,79
87,Robert Simon,A,173.020756,60.642721,2006-10-09,19,16,58,54,92,13,71,79,39
88,Ryan Simmons,A,161.173288,99.428801,2006-10-17,79,99,6,96,4,10,44,59,37
105,Natalie Daniels,A,180.376300,49.575043,2005-03-30,5,91,31,76,76,30,84,84,31
116,Brian Hicks,A,177.920751,47.726049,2007-03-23,34,44,81,39,94,8,88,32,28
119,Jeremy Taylor,A,170.505545,50.525915,2007-01-28,83,89,87,51,69,14,35,4,48
134,Charles Davila,A,167.465797,97.684109,2005-09-25,65,84,91,86,16,30,54,74,90
136,Kevin Swanson,A,165.174903,36.023448,2006-07-05,23,30,8,11,89,16,99,47,46
141,Stephanie Stone,A,180.817496,64.455338,2005-05-16,54,52,46,2,14,7,21,17,44
144,John Anderson,A,170.624079,93.535124,2005-02-28,40,61,39,33,28,2,49,43,64
151,Troy Wyatt,A,180.084012,74.096006,2004-06-20,50,70,23,82,39,8,52,43,80
162,Craig Wood,A,160.204346,83.205547,2006-10-23,9,51,90,27,95,6,87,61,5
166,Justin Stewart,A,163.721595,76.123517,2004-05-31,89,100,41,98,83,5,57,99,29
176,Gina Wheeler,A,176.908225,62.662457,2005-10-08,96,5,26,48,62,15,30,62,76
180,Dawn Montoya,A,188.853744,44.008385,2004-08-12,1,9,91,84,99,29,75,17,4
190,Alexis Spencer,A,183.907812,82.761173,2006-07-26,12,27,34,97,57,9,27,8,90
194,Elizabeth Robinson,A,177.788317,71.787728,2006-11-14,91,54,85,88,94,11,0,82,36
196,Tyler Donovan,A,173.240999,82.156297,2004-12-06,28,73,23,7,42,13,75,73,12
201,Jack Walter,A,165.534998,69.745570,2005-10-28,40,97,14,20,87,15,11,10,33
214,Olivia Martinez,A,169.483592,72.472046,2006-03-22,84,70,61,15,20,0,6,75,2
224,Curtis Brown,A,167.539398,92.328258,2006-01-13,44,81,34,34,1,2,68,32,59
227,Francisco Walter,A,178.818653,38.098505,2006-03-04,76,81,96,55,94,29,2,21,89
238,Jason Mendez,A,162.263195,96.078623,2005-04-09,51,34,37,4,58,7,7,87,60
247,Denise Stanton,A,185.196570,58.103004,2005-03-15,13,43,33,3,73,13,46,89,44
250,Martha Maxwell,A,168.582580,95.810557,2006-01-27,11,5,30,11,17,19,41,66,47
252,Jeffery Walls,A,187.830312,63.805195,2005-10-21,66,34,69,48,44,25,44,22,98
256,Victoria Taylor,A,160.002126,93.294443,2007-03-15,27,76,27,9,94,19,46,73,24
260,Sarah Hess,A,168.894706,96.298982,2006-06-01,2,21,32,37,96,3,30,25,85
268,Eric Townsend,A,161.298998,64.787811,2007-02-28,13,55,48,74,34,18,71,5,64
269,Benjamin Turner,A,175.432034,57.966287,2005-11-22,16,86,38,27,85,14,46,28,8
271,Jason Hernandez,A,178.789542,66.712362,2005-10-22,90,21,29,85,98,14,68,19,37
276,Carol Palmer,A,185.948742,69.342926,2004-11-21,12,51,16,77,52,0,81,32,20

In [ ]:
student_data.groupby(["Group"]) ['Name'].count().reset_index()

  Group  Name
0     A    94
1     B    95
2     C   111

In [ ]:
student_data.groupby(["Group"]) ['Weight'].sum().reset_index()

  Group       Weight
0     A  6101.885831
1     B  6414.941907
2     C  7574.692803

In [ ]:
student_data.groupby(["Group"]) ['Maths_Quiz_Score'].mean().reset_index()

  Group  Maths_Quiz_Score
0     A         53.042553
1     B         52.936842
2     C         53.378378

In [ ]:
min = student_data.groupby(["Group"]) ['Weight'].min().reset_index()
max = student_data.groupby(["Group"]) ['Weight'].max().reset_index()

In [ ]:
min = student_data.groupby(["Group"]) ['Height'].min().reset_index()
max = student_data.groupby(["Group"]) ['Height'].max().reset_index()

In [ ]:
science_test = student_data.groupby(["Group"]) ['Science_Test_Score'].mean().reset_index()
smallest_math_test = student_data.groupby(["Group"]) ['Maths_Test_Score'].min().loc['B']

In [ ]:
student_data.loc[50, "Name"] = "Shawn Clark"

In [ ]:
student_data.loc[50]

Name                           Shawn Clark
Group                                    C
Height                          144.945785
Weight                           45.159664
Date_of_Birth                   2006-06-08
Maths_Test_Score                         2
Maths_Quiz_Score                        67
Maths_Assignment_Score                  43
Science_Test_Score                      61
Science_Quiz_Score                      36
Science_Assignment_Score                 8
Literature_Test_Score                   35
Literature_Quiz_Score                   19
Literature_Assignment_Score             26
Name: 50, dtype: object

In [12]:
new_data = {
    "Name": ['Aldi', 'Tika', 'Michael Jung', 'Ronald'],
    "Group": ['A', 'B', 'A', 'A'],
    'Height': [147, 150, 184, 139],
    "Weight": [47, 39, 42,45]
}

new_dataframe = pd.DataFrame(new_data)
student_data = student_data._append(new_dataframe, ignore_index = True)

In [13]:
student_data.tail(20)

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
284,Andrew Solomon,C,159.019225,74.392341,2004-10-13,30.0,90.0,36.0,85.0,50.0,19.0,31.0,74.0,59.0
285,Michelle Carson,A,148.757399,76.580334,2006-06-15,62.0,19.0,84.0,95.0,68.0,0.0,85.0,51.0,41.0
286,Sarah Smith,A,151.540240,68.237031,2006-09-12,55.0,73.0,49.0,66.0,78.0,24.0,12.0,40.0,63.0
287,Joshua Bass,B,137.544748,48.370082,2004-06-08,65.0,44.0,0.0,33.0,93.0,24.0,95.0,44.0,28.0
288,Andrea Roberts,C,174.719137,79.828943,2006-06-07,42.0,25.0,68.0,25.0,3.0,8.0,82.0,36.0,13.0
289,Gerald Mitchell,B,166.906225,90.256385,2005-08-10,6.0,28.0,92.0,83.0,14.0,5.0,25.0,35.0,20.0
290,Nicholas Andrews,B,188.017360,61.279627,2005-04-28,2.0,19.0,99.0,32.0,88.0,1.0,14.0,27.0,27.0
291,Heather Olson,C,142.748380,86.072978,2007-04-19,54.0,27.0,92.0,2.0,13.0,16.0,30.0,41.0,31.0
292,Ryan Arnold,A,138.557409,45.726217,2006-08-25,58.0,86.0,22.0,84.0,32.0,27.0,49.0,72.0,88.0
293,Erica Pierce,C,157.149145,76.763277,2005-12-17,100.0,65.0,20.0,47.0,42.0,5.0,52.0,71.0,61.0
294,Dawn Martinez,B,188.462033,87.264918,2005-06-02,25.0,29.0,23.0,15.0,16.0,14.0,66.0,69.0,4.0
295,Shannon Hardy,B,169.467107,84.571455,2007-03-23,79.0,85.0,96.0,75.0,94.0,9.0,65.0,40.0,57.0
296,Christopher Ware,A,152.802949,44.157204,2006-08-31,24.0,65.0,22.0,99.0,78.0,13.0,80.0,87.0,2.0
297,Christina Thomas,C,143.430767,99.893619,2004-06-10,27.0,31.0,44.0,36.0,96.0,18.0,15.0,79.0,1.0
298,Mark Esparza,C,186.765477,70.029551,2006-08-30,10.0,39.0,59.0,3.0,67.0,15.0,3.0,100.0,7.0
299,William Foster,B,153.790174,90.010683,2004-05-18,32.0,73.0,60.0,24.0,62.0,15.0,62.0,13.0,30.0
300,Aldi,A,147.000000,47.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,Tika,B,150.000000,39.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,Michael Jung,A,184.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,Ronald,A,139.000000,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
student_data["Math_Score"] = (student_data["Maths_Test_Score"] + student_data["Maths_Quiz_Score"] + student_data["Maths_Assignment_Score"])/3

In [11]:
student_data = student_data.drop("Math_Score", axis=1)
student_data.tail()

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
295,Shannon Hardy,B,169.467107,84.571455,2007-03-23,79,85,96,75,94,9,65,40,57
296,Christopher Ware,A,152.802949,44.157204,2006-08-31,24,65,22,99,78,13,80,87,2
297,Christina Thomas,C,143.430767,99.893619,2004-06-10,27,31,44,36,96,18,15,79,1
298,Mark Esparza,C,186.765477,70.029551,2006-08-30,10,39,59,3,67,15,3,100,7
299,William Foster,B,153.790174,90.010683,2004-05-18,32,73,60,24,62,15,62,13,30

In [14]:
student_data = student_data.drop(303)
student_data.tail()

,Name,Group,Height,Weight,Date_of_Birth,Maths_Test_Score,Maths_Quiz_Score,Maths_Assignment_Score,Science_Test_Score,Science_Quiz_Score,Science_Assignment_Score,Literature_Test_Score,Literature_Quiz_Score,Literature_Assignment_Score
298,Mark Esparza,C,186.765477,70.029551,2006-08-30,10.0,39.0,59.0,3.0,67.0,15.0,3.0,100.0,7.0
299,William Foster,B,153.790174,90.010683,2004-05-18,32.0,73.0,60.0,24.0,62.0,15.0,62.0,13.0,30.0
300,Aldi,A,147.000000,47.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,Tika,B,150.000000,39.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,Michael Jung,A,184.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN